### ISSUE TITLE
AppImage desktop integration tools

### ISSUE THREAD

**Issue by probonopd** [Diamonman123/Appimage-installer#1]
Not an issue, but I thought you might be interested in this collection of existing tools:
https://github.com/AppImage/awesome-appimage#desktop-integration

**Comment by Diamonman123** [comment]
This is just meant to be a universal script, wrote in pure shell. My goal is to make a tiny installer that is comparable on non deb and rpm compatible machines. It means no dependencies and no bloat.
It is just a usb loadable tool for the few situations that calls for it, not to compete with existing software
